apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno01011
  namespace: sno01011
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno01011"
  labels:
    infraenvs.agent-install.openshift.io: "sno01011"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.115:9000/redfish/v1/Systems/d35cb0b8-21c2-4c30-a11c-c9a8c9072897'
    disableCertificateVerification: true
    credentialsName: sno01011-bmc-secret
  bootMACAddress: '52:54:00:76:61:02'
  automatedCleaningMode: disabled
  online: true
