apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00925
  namespace: sno00925
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00925"
  labels:
    infraenvs.agent-install.openshift.io: "sno00925"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.102:9000/redfish/v1/Systems/323c4d18-7aec-48a3-a848-8b8604c27e20'
    disableCertificateVerification: true
    credentialsName: sno00925-bmc-secret
  bootMACAddress: '52:54:00:76:54:11'
  automatedCleaningMode: disabled
  online: true
