apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00968
  namespace: sno00968
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00968"
  labels:
    infraenvs.agent-install.openshift.io: "sno00968"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.109:9000/redfish/v1/Systems/ec2c4dbf-bb79-4a20-b4b7-a197d2f316a4'
    disableCertificateVerification: true
    credentialsName: sno00968-bmc-secret
  bootMACAddress: '52:54:00:76:5b:01'
  automatedCleaningMode: disabled
  online: true
