apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00632
  namespace: sno00632
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00632"
  labels:
    infraenvs.agent-install.openshift.io: "sno00632"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.72:9000/redfish/v1/Systems/ef08c2ac-1b07-46e8-85a7-cb998b55081a'
    disableCertificateVerification: true
    credentialsName: sno00632-bmc-secret
  bootMACAddress: '52:54:00:76:36:04'
  automatedCleaningMode: disabled
  online: true
