apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00782
  namespace: sno00782
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00782"
  labels:
    infraenvs.agent-install.openshift.io: "sno00782"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.88:9000/redfish/v1/Systems/ff374492-2945-46c2-83fa-8dde1947b608'
    disableCertificateVerification: true
    credentialsName: sno00782-bmc-secret
  bootMACAddress: '52:54:00:76:46:02'
  automatedCleaningMode: disabled
  online: true
