apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00920
  namespace: sno00920
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00920"
  labels:
    infraenvs.agent-install.openshift.io: "sno00920"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.102:9000/redfish/v1/Systems/bae28456-795e-415e-bd9f-731aafa03515'
    disableCertificateVerification: true
    credentialsName: sno00920-bmc-secret
  bootMACAddress: '52:54:00:76:54:0c'
  automatedCleaningMode: disabled
  online: true
