apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00836
  namespace: sno00836
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00836"
  labels:
    infraenvs.agent-install.openshift.io: "sno00836"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.95:9000/redfish/v1/Systems/1ac1fab7-778a-4ba9-85cd-b835f09b67b9'
    disableCertificateVerification: true
    credentialsName: sno00836-bmc-secret
  bootMACAddress: '52:54:00:76:4d:07'
  automatedCleaningMode: disabled
  online: true
