apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00788
  namespace: sno00788
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00788"
  labels:
    infraenvs.agent-install.openshift.io: "sno00788"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.89:9000/redfish/v1/Systems/3068787d-ab0d-4b24-8137-844b3a38946f'
    disableCertificateVerification: true
    credentialsName: sno00788-bmc-secret
  bootMACAddress: '52:54:00:76:47:01'
  automatedCleaningMode: disabled
  online: true
