apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00969
  namespace: sno00969
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00969"
  labels:
    infraenvs.agent-install.openshift.io: "sno00969"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.109:9000/redfish/v1/Systems/e8db6643-2ca0-4a98-b849-f6df3dcc30e6'
    disableCertificateVerification: true
    credentialsName: sno00969-bmc-secret
  bootMACAddress: '52:54:00:76:5b:02'
  automatedCleaningMode: disabled
  online: true
