apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00630
  namespace: sno00630
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00630"
  labels:
    infraenvs.agent-install.openshift.io: "sno00630"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.72:9000/redfish/v1/Systems/38665d20-5a48-46c1-90ac-6fc778dc3a6c'
    disableCertificateVerification: true
    credentialsName: sno00630-bmc-secret
  bootMACAddress: '52:54:00:76:36:02'
  automatedCleaningMode: disabled
  online: true
