apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00716
  namespace: sno00716
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00716"
  labels:
    infraenvs.agent-install.openshift.io: "sno00716"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.83:9000/redfish/v1/Systems/644053b1-0dfe-4e9f-a4cc-45d2c6f71878'
    disableCertificateVerification: true
    credentialsName: sno00716-bmc-secret
  bootMACAddress: '52:54:00:76:41:0b'
  automatedCleaningMode: disabled
  online: true
