apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00809
  namespace: sno00809
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00809"
  labels:
    infraenvs.agent-install.openshift.io: "sno00809"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.92:9000/redfish/v1/Systems/c9d37a11-9afc-4b4b-886a-774fe38c5419'
    disableCertificateVerification: true
    credentialsName: sno00809-bmc-secret
  bootMACAddress: '52:54:00:76:4a:01'
  automatedCleaningMode: disabled
  online: true
