apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00700
  namespace: sno00700
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00700"
  labels:
    infraenvs.agent-install.openshift.io: "sno00700"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.82:9000/redfish/v1/Systems/20fca260-1a5c-4875-ba1b-a05d8f9d83c8'
    disableCertificateVerification: true
    credentialsName: sno00700-bmc-secret
  bootMACAddress: '52:54:00:76:40:02'
  automatedCleaningMode: disabled
  online: true
