apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00833
  namespace: sno00833
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00833"
  labels:
    infraenvs.agent-install.openshift.io: "sno00833"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.95:9000/redfish/v1/Systems/b59b0b4f-6aab-491d-a70c-8fcd8c90d455'
    disableCertificateVerification: true
    credentialsName: sno00833-bmc-secret
  bootMACAddress: '52:54:00:76:4d:04'
  automatedCleaningMode: disabled
  online: true
