apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00712
  namespace: sno00712
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00712"
  labels:
    infraenvs.agent-install.openshift.io: "sno00712"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.83:9000/redfish/v1/Systems/17a8aa2e-aedd-4e95-bdfe-903b86fdd781'
    disableCertificateVerification: true
    credentialsName: sno00712-bmc-secret
  bootMACAddress: '52:54:00:76:41:07'
  automatedCleaningMode: disabled
  online: true
