apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00762
  namespace: sno00762
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00762"
  labels:
    infraenvs.agent-install.openshift.io: "sno00762"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.86:9000/redfish/v1/Systems/6e902ffe-b5d4-48e4-8336-4b4c55b07874'
    disableCertificateVerification: true
    credentialsName: sno00762-bmc-secret
  bootMACAddress: '52:54:00:76:44:06'
  automatedCleaningMode: disabled
  online: true
