apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00683
  namespace: sno00683
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00683"
  labels:
    infraenvs.agent-install.openshift.io: "sno00683"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.79:9000/redfish/v1/Systems/018083bc-7810-4e22-adff-f1237f637d5a'
    disableCertificateVerification: true
    credentialsName: sno00683-bmc-secret
  bootMACAddress: '52:54:00:76:3d:06'
  automatedCleaningMode: disabled
  online: true
