apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00914
  namespace: sno00914
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00914"
  labels:
    infraenvs.agent-install.openshift.io: "sno00914"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.102:9000/redfish/v1/Systems/1d3e1ad1-0de4-4371-bfc9-149462783dc1'
    disableCertificateVerification: true
    credentialsName: sno00914-bmc-secret
  bootMACAddress: '52:54:00:76:54:06'
  automatedCleaningMode: disabled
  online: true
