apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00607
  namespace: sno00607
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00607"
  labels:
    infraenvs.agent-install.openshift.io: "sno00607"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.68:9000/redfish/v1/Systems/e9024a89-c286-40c6-921a-13402250640b'
    disableCertificateVerification: true
    credentialsName: sno00607-bmc-secret
  bootMACAddress: '52:54:00:76:32:07'
  automatedCleaningMode: disabled
  online: true
