apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00810
  namespace: sno00810
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00810"
  labels:
    infraenvs.agent-install.openshift.io: "sno00810"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.92:9000/redfish/v1/Systems/edbc40ba-c36b-416a-b6ce-ff0e5894aa37'
    disableCertificateVerification: true
    credentialsName: sno00810-bmc-secret
  bootMACAddress: '52:54:00:76:4a:02'
  automatedCleaningMode: disabled
  online: true
