apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00916
  namespace: sno00916
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00916"
  labels:
    infraenvs.agent-install.openshift.io: "sno00916"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.102:9000/redfish/v1/Systems/cf6fd46e-faa1-43f0-ab10-694305476fe4'
    disableCertificateVerification: true
    credentialsName: sno00916-bmc-secret
  bootMACAddress: '52:54:00:76:54:08'
  automatedCleaningMode: disabled
  online: true
