apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00603
  namespace: sno00603
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00603"
  labels:
    infraenvs.agent-install.openshift.io: "sno00603"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.68:9000/redfish/v1/Systems/24499539-b449-4196-9c3c-de264d888902'
    disableCertificateVerification: true
    credentialsName: sno00603-bmc-secret
  bootMACAddress: '52:54:00:76:32:03'
  automatedCleaningMode: disabled
  online: true
