apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00779
  namespace: sno00779
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00779"
  labels:
    infraenvs.agent-install.openshift.io: "sno00779"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.87:9000/redfish/v1/Systems/cf9f5178-d717-4a92-9bb5-ad9056ee6a1c'
    disableCertificateVerification: true
    credentialsName: sno00779-bmc-secret
  bootMACAddress: '52:54:00:76:45:06'
  automatedCleaningMode: disabled
  online: true
