apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00776
  namespace: sno00776
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00776"
  labels:
    infraenvs.agent-install.openshift.io: "sno00776"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.87:9000/redfish/v1/Systems/2532b371-d14b-427d-b0a3-6dec3d70839d'
    disableCertificateVerification: true
    credentialsName: sno00776-bmc-secret
  bootMACAddress: '52:54:00:76:45:03'
  automatedCleaningMode: disabled
  online: true
