apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00697
  namespace: sno00697
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00697"
  labels:
    infraenvs.agent-install.openshift.io: "sno00697"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.81:9000/redfish/v1/Systems/d9476e13-903d-4544-995a-ded9bee67038'
    disableCertificateVerification: true
    credentialsName: sno00697-bmc-secret
  bootMACAddress: '52:54:00:76:3f:06'
  automatedCleaningMode: disabled
  online: true
