apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00777
  namespace: sno00777
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00777"
  labels:
    infraenvs.agent-install.openshift.io: "sno00777"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.87:9000/redfish/v1/Systems/698d7264-a5d0-4306-aa7d-79fe3760be00'
    disableCertificateVerification: true
    credentialsName: sno00777-bmc-secret
  bootMACAddress: '52:54:00:76:45:04'
  automatedCleaningMode: disabled
  online: true
