apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00995
  namespace: sno00995
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00995"
  labels:
    infraenvs.agent-install.openshift.io: "sno00995"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.112:9000/redfish/v1/Systems/bfe7112b-49e9-446f-be1c-fea196638428'
    disableCertificateVerification: true
    credentialsName: sno00995-bmc-secret
  bootMACAddress: '52:54:00:76:5e:07'
  automatedCleaningMode: disabled
  online: true
