apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00882
  namespace: sno00882
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00882"
  labels:
    infraenvs.agent-install.openshift.io: "sno00882"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.100:9000/redfish/v1/Systems/32be87e4-6549-4c1b-bf23-bbc018fa75b0'
    disableCertificateVerification: true
    credentialsName: sno00882-bmc-secret
  bootMACAddress: '52:54:00:76:52:08'
  automatedCleaningMode: disabled
  online: true
