apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00813
  namespace: sno00813
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00813"
  labels:
    infraenvs.agent-install.openshift.io: "sno00813"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.92:9000/redfish/v1/Systems/d8d82b58-04d1-48fe-aa88-a01eeb9c95fe'
    disableCertificateVerification: true
    credentialsName: sno00813-bmc-secret
  bootMACAddress: '52:54:00:76:4a:05'
  automatedCleaningMode: disabled
  online: true
