apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00674
  namespace: sno00674
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00674"
  labels:
    infraenvs.agent-install.openshift.io: "sno00674"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.78:9000/redfish/v1/Systems/d8eba07e-13db-41a7-9738-017f1825c54d'
    disableCertificateVerification: true
    credentialsName: sno00674-bmc-secret
  bootMACAddress: '52:54:00:76:3c:04'
  automatedCleaningMode: disabled
  online: true
