apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00704
  namespace: sno00704
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00704"
  labels:
    infraenvs.agent-install.openshift.io: "sno00704"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.82:9000/redfish/v1/Systems/fb0acc7e-a87e-4bac-b124-88ab949b8873'
    disableCertificateVerification: true
    credentialsName: sno00704-bmc-secret
  bootMACAddress: '52:54:00:76:40:06'
  automatedCleaningMode: disabled
  online: true
