apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno01014
  namespace: sno01014
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno01014"
  labels:
    infraenvs.agent-install.openshift.io: "sno01014"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.115:9000/redfish/v1/Systems/27d74414-d41d-4615-b0f1-73cee409f886'
    disableCertificateVerification: true
    credentialsName: sno01014-bmc-secret
  bootMACAddress: '52:54:00:76:61:05'
  automatedCleaningMode: disabled
  online: true
