apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00981
  namespace: sno00981
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00981"
  labels:
    infraenvs.agent-install.openshift.io: "sno00981"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.110:9000/redfish/v1/Systems/308b816d-3676-4b7c-9b52-7f57b5cf61e9'
    disableCertificateVerification: true
    credentialsName: sno00981-bmc-secret
  bootMACAddress: '52:54:00:76:5c:07'
  automatedCleaningMode: disabled
  online: true
