apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00665
  namespace: sno00665
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00665"
  labels:
    infraenvs.agent-install.openshift.io: "sno00665"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.77:9000/redfish/v1/Systems/53e6e2cb-9add-4f1d-990a-0b30c117dc99'
    disableCertificateVerification: true
    credentialsName: sno00665-bmc-secret
  bootMACAddress: '52:54:00:76:3b:02'
  automatedCleaningMode: disabled
  online: true
