apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00660
  namespace: sno00660
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00660"
  labels:
    infraenvs.agent-install.openshift.io: "sno00660"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.76:9000/redfish/v1/Systems/41ef21d1-5e34-46e0-b83e-a09cece576c2'
    disableCertificateVerification: true
    credentialsName: sno00660-bmc-secret
  bootMACAddress: '52:54:00:76:3a:04'
  automatedCleaningMode: disabled
  online: true
