apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00909
  namespace: sno00909
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00909"
  labels:
    infraenvs.agent-install.openshift.io: "sno00909"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.102:9000/redfish/v1/Systems/f01ab9d2-36a0-4858-bd82-93848a533252'
    disableCertificateVerification: true
    credentialsName: sno00909-bmc-secret
  bootMACAddress: '52:54:00:76:54:01'
  automatedCleaningMode: disabled
  online: true
