apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00802
  namespace: sno00802
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00802"
  labels:
    infraenvs.agent-install.openshift.io: "sno00802"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.91:9000/redfish/v1/Systems/e626d7da-6dcd-40ea-a3c3-8098f9321721'
    disableCertificateVerification: true
    credentialsName: sno00802-bmc-secret
  bootMACAddress: '52:54:00:76:49:01'
  automatedCleaningMode: disabled
  online: true
