apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00722
  namespace: sno00722
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00722"
  labels:
    infraenvs.agent-install.openshift.io: "sno00722"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.83:9000/redfish/v1/Systems/98518465-4ac8-439f-956f-40152b36bfc7'
    disableCertificateVerification: true
    credentialsName: sno00722-bmc-secret
  bootMACAddress: '52:54:00:76:41:11'
  automatedCleaningMode: disabled
  online: true
