apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00709
  namespace: sno00709
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00709"
  labels:
    infraenvs.agent-install.openshift.io: "sno00709"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.83:9000/redfish/v1/Systems/6f70618a-3c45-4c51-8620-8e7b94bfd643'
    disableCertificateVerification: true
    credentialsName: sno00709-bmc-secret
  bootMACAddress: '52:54:00:76:41:04'
  automatedCleaningMode: disabled
  online: true
