apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00785
  namespace: sno00785
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00785"
  labels:
    infraenvs.agent-install.openshift.io: "sno00785"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.88:9000/redfish/v1/Systems/5b02b45c-19f5-46c6-97fa-ba9015b5fba4'
    disableCertificateVerification: true
    credentialsName: sno00785-bmc-secret
  bootMACAddress: '52:54:00:76:46:05'
  automatedCleaningMode: disabled
  online: true
