apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno01006
  namespace: sno01006
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno01006"
  labels:
    infraenvs.agent-install.openshift.io: "sno01006"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.114:9000/redfish/v1/Systems/22409c16-9339-4a8e-94c7-ad4a8946b0a6'
    disableCertificateVerification: true
    credentialsName: sno01006-bmc-secret
  bootMACAddress: '52:54:00:76:60:04'
  automatedCleaningMode: disabled
  online: true
