apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00763
  namespace: sno00763
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00763"
  labels:
    infraenvs.agent-install.openshift.io: "sno00763"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.86:9000/redfish/v1/Systems/e5edb607-cc84-4736-86a0-a870e9446c32'
    disableCertificateVerification: true
    credentialsName: sno00763-bmc-secret
  bootMACAddress: '52:54:00:76:44:07'
  automatedCleaningMode: disabled
  online: true
