apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00703
  namespace: sno00703
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00703"
  labels:
    infraenvs.agent-install.openshift.io: "sno00703"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.82:9000/redfish/v1/Systems/c0417b00-558a-4140-87bf-1876f0e410a4'
    disableCertificateVerification: true
    credentialsName: sno00703-bmc-secret
  bootMACAddress: '52:54:00:76:40:05'
  automatedCleaningMode: disabled
  online: true
