apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00915
  namespace: sno00915
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00915"
  labels:
    infraenvs.agent-install.openshift.io: "sno00915"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.102:9000/redfish/v1/Systems/95e69391-f7ed-4c24-b6d1-c74196cc49e0'
    disableCertificateVerification: true
    credentialsName: sno00915-bmc-secret
  bootMACAddress: '52:54:00:76:54:07'
  automatedCleaningMode: disabled
  online: true
