apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00837
  namespace: sno00837
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00837"
  labels:
    infraenvs.agent-install.openshift.io: "sno00837"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.96:9000/redfish/v1/Systems/1e7441cc-0175-452d-a463-d522553bbec7'
    disableCertificateVerification: true
    credentialsName: sno00837-bmc-secret
  bootMACAddress: '52:54:00:76:4e:01'
  automatedCleaningMode: disabled
  online: true
